"""network devices services cameras alerts automation"""
from alembic import op
import sqlalchemy as sa

revision = "0002_operations"
down_revision = "0001_foundation"
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("devices", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(120), nullable=False), sa.Column("kind", sa.String(40), nullable=False), sa.Column("manufacturer", sa.String(100)), sa.Column("protocol", sa.String(40), nullable=False), sa.Column("address", sa.String(255)), sa.Column("mac_address", sa.String(17)), sa.Column("capabilities", sa.Text(), nullable=False), sa.Column("is_enabled", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)); op.create_index("ix_devices_name", "devices", ["name"])
    op.create_table("network_hosts", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("hostname", sa.String(255)), sa.Column("ip_address", sa.String(64), nullable=False), sa.Column("mac_address", sa.String(17)), sa.Column("vendor", sa.String(120)), sa.Column("status", sa.String(20), nullable=False), sa.Column("latency_ms", sa.Float()), sa.Column("last_seen", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)); op.create_index("ix_network_hosts_ip_address", "network_hosts", ["ip_address"], unique=True)
    op.create_table("status_samples", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("host_id", sa.Integer(), sa.ForeignKey("network_hosts.id"), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("latency_ms", sa.Float()), sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False)); op.create_index("ix_status_samples_host_id", "status_samples", ["host_id"]); op.create_index("ix_status_samples_recorded_at", "status_samples", ["recorded_at"])
    op.create_table("service_units", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(120), nullable=False), sa.Column("unit_name", sa.String(120), nullable=False), sa.Column("enabled_actions", sa.String(100), nullable=False), sa.Column("is_enabled", sa.Boolean(), nullable=False)); op.create_index("ix_service_units_unit_name", "service_units", ["unit_name"], unique=True)
    op.create_table("cameras", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(120), nullable=False), sa.Column("address", sa.String(255), nullable=False), sa.Column("protocol", sa.String(20), nullable=False), sa.Column("snapshot_url", sa.String(500)), sa.Column("enabled", sa.Boolean(), nullable=False), sa.Column("last_status", sa.String(20), nullable=False))
    op.create_table("alerts", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("event_type", sa.String(100), nullable=False), sa.Column("severity", sa.String(20), nullable=False), sa.Column("message", sa.Text(), nullable=False), sa.Column("is_acknowledged", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)); op.create_index("ix_alerts_event_type", "alerts", ["event_type"]); op.create_index("ix_alerts_created_at", "alerts", ["created_at"])
    op.create_table("automation_rules", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(120), nullable=False), sa.Column("trigger_type", sa.String(100), nullable=False), sa.Column("condition_json", sa.Text(), nullable=False), sa.Column("action_type", sa.String(100), nullable=False), sa.Column("action_json", sa.Text(), nullable=False), sa.Column("enabled", sa.Boolean(), nullable=False))

def downgrade():
    op.drop_table("automation_rules"); op.drop_index("ix_alerts_created_at", table_name="alerts"); op.drop_index("ix_alerts_event_type", table_name="alerts"); op.drop_table("alerts"); op.drop_table("cameras"); op.drop_index("ix_service_units_unit_name", table_name="service_units"); op.drop_table("service_units"); op.drop_index("ix_status_samples_recorded_at", table_name="status_samples"); op.drop_index("ix_status_samples_host_id", table_name="status_samples"); op.drop_table("status_samples"); op.drop_index("ix_network_hosts_ip_address", table_name="network_hosts"); op.drop_table("network_hosts"); op.drop_index("ix_devices_name", table_name="devices"); op.drop_table("devices")
